### ISSUE TITLE
Add pull request workflow and nightly release workflow

### ISSUE THREAD

**Issue by JensvandeWiel** [JensvandeWiel/ArkAscendedServerManager#32]

**Comment by JensvandeWiel** [comment]
https://github.com/marketplace/actions/nightly-release

**Comment by JensvandeWiel** [comment]
For pull requests:
```
name: AASM Pull Request Build

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: Ark-Ascended-Server-Manager.exe
            platform: windows/amd64
            os: windows-latest
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set direct proxy
        run: go env -w GOPROXY=direct
      - run: go install github.com/wailsapp/wails/cmd/wails@latest
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          build: true
          nsis: true
          package: false
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AASM Artifacts
          path: build/bin/*.exe
```

**Comment by JensvandeWiel** [comment]
For: Nightly builds:
```
name: Nightly AASM Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'  # Replace with your desired Go version

      - name: Build code
        run: |
          go env -w GOPROXY=direct
          go install github.com/wailsapp/wails/cmd/wails@latest
          # Add commands to build your code here

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AASM Installer
          path: build/bin/*.exe

      - name: Upload Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Desktop App Nightly Release ${{ github.run_number }}'
          prerelease: true
          body: 'This is a nightly release of the AASM. It's unstable compared to the official releases, use it with caution!'
          files: |
            build/bin/*.exe

```
